<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContactsTableSeeder extends Seeder
{
    public function run(): void
    {
        // 🔹 Insertar 5 deudores
        DB::table('debtors')->insert([
            [
                'tipo_cedente' => 'publico',
                'nombre_cedente' => 'Cedente 1',
                'nombre_deudor' => 'Deudor 1',
                'monto_deuda_total' => 1000,
                'diagnostico' => 'CP',
                'estado' => 'Asignacion',
                'judicial' => true,
                'ultima_gestion' => now(),
                'tipo_ultima_gestion' => 'Llamada',
                'proxima_gestion' => now()->addDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tipo_cedente' => 'privado',
                'nombre_cedente' => 'Cedente 2',
                'nombre_deudor' => 'Deudor 2',
                'monto_deuda_total' => 2500,
                'diagnostico' => 'PP',
                'estado' => 'Investigacion',
                'judicial' => false,
                'ultima_gestion' => now(),
                'tipo_ultima_gestion' => 'Email',
                'proxima_gestion' => now()->addDays(3),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tipo_cedente' => 'publico',
                'nombre_cedente' => 'Cedente 3',
                'nombre_deudor' => 'Deudor 3',
                'monto_deuda_total' => 500,
                'diagnostico' => 'NP',
                'estado' => 'Contactabilidad',
                'judicial' => true,
                'ultima_gestion' => now(),
                'tipo_ultima_gestion' => 'Visita',
                'proxima_gestion' => now()->addDays(7),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tipo_cedente' => 'privado',
                'nombre_cedente' => 'Cedente 4',
                'nombre_deudor' => 'Deudor 4',
                'monto_deuda_total' => 750,
                'diagnostico' => 'NQP',
                'estado' => 'Negociacion',
                'judicial' => false,
                'ultima_gestion' => now(),
                'tipo_ultima_gestion' => 'Llamada',
                'proxima_gestion' => now()->addDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tipo_cedente' => 'publico',
                'nombre_cedente' => 'Cedente 5',
                'nombre_deudor' => 'Deudor 5',
                'monto_deuda_total' => 1200,
                'diagnostico' => 'CONT',
                'estado' => 'Seguimiento',
                'judicial' => true,
                'ultima_gestion' => now(),
                'tipo_ultima_gestion' => 'Email',
                'proxima_gestion' => now()->addDays(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 🔹 Insertar 10 contactos asociados a los deudores
        DB::table('contacts')->insert([
            [
                'debtor_id' => 1,
                'categoria' => 'personal',
                'tipo' => 'celular',
                'detalle' => '0998765432',
                'validacion' => true,
                'principal' => true,
                'observacion' => 'Contacto principal',
                'fecha_validacion' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'debtor_id' => 1,
                'categoria' => 'trabajo',
                'tipo' => 'email',
                'detalle' => 'contacto1@empresa.com',
                'validacion' => false,
                'principal' => false,
                'observacion' => 'Email de trabajo',
                'fecha_validacion' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'debtor_id' => 2,
                'categoria' => 'familiar',
                'tipo' => 'telefono_fijo',
                'detalle' => '022334455',
                'validacion' => true,
                'principal' => true,
                'observacion' => 'Llamar después de las 6 pm',
                'fecha_validacion' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'debtor_id' => 2,
                'categoria' => 'cobranza',
                'tipo' => 'celular',
                'detalle' => '0991234567',
                'validacion' => false,
                'principal' => false,
                'observacion' => 'Número alternativo',
                'fecha_validacion' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'debtor_id' => 3,
                'categoria' => 'legal',
                'tipo' => 'email',
                'detalle' => 'legal@empresa.com',
                'validacion' => true,
                'principal' => true,
                'observacion' => 'Enviar notificación legal',
                'fecha_validacion' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'debtor_id' => 3,
                'categoria' => 'referencia',
                'tipo' => 'celular',
                'detalle' => '0999988776',
                'validacion' => false,
                'principal' => false,
                'observacion' => 'Contacto de referencia',
                'fecha_validacion' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'debtor_id' => 4,
                'categoria' => 'trabajo',
                'tipo' => 'direccion',
                'detalle' => 'Av. Quito 123',
                'validacion' => true,
                'principal' => true,
                'observacion' => 'Oficina principal',
                'fecha_validacion' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'debtor_id' => 4,
                'categoria' => 'personal',
                'tipo' => 'celular',
                'detalle' => '0994455667',
                'validacion' => false,
                'principal' => false,
                'observacion' => 'Contacto secundario',
                'fecha_validacion' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'debtor_id' => 5,
                'categoria' => 'referencia',
                'tipo' => 'email',
                'detalle' => 'ref@contacto.com',
                'validacion' => true,
                'principal' => true,
                'observacion' => 'Referencia laboral',
                'fecha_validacion' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'debtor_id' => 5,
                'categoria' => 'familiar',
                'tipo' => 'telefono_fijo',
                'detalle' => '022112233',
                'validacion' => false,
                'principal' => false,
                'observacion' => 'Número de hermano',
                'fecha_validacion' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
